start_as normal


# Wygląd okna i marginesy
window_padding_width 4
# --- Konfiguracja przezroczystości i rozmycia w Kitty ---
background_opacity 0.7
background_blur 32
# Ustawienia kursora
cursor_shape block
cursor_blink_interval 0.5

# Dźwięki powiadomień (wyłączenie "piknięcia")
enable_audio_bell no


include themes/noctalia.conf

font_size        13

text_composition_strategy 1.0 30
# font_family      Iosevka NF ExtraBold


# BEGIN_KITTY_FONTS
font_family      family="ProFont IIx Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS