-- binds.lua

-- 1. System & UI
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"), { release = true, description = "Open App Launcher" })
hl.unbind("SUPER + slash")
hl.bind("SUPER + slash", hl.dsp.exec_cmd("noctalia msg panel-toggle kenn/keybind-cheatsheet:cheatsheet"), { description = "Toggle Keybind Cheatsheet" })
hl.unbind("CTRL + Insert")
hl.bind("CTRL + Insert", hl.dsp.exec_cmd("noctalia msg screenshot-region"), { description = "Take region screenshot" })

-- 2. Applications
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("zen-browser"), { description = "Open Web Browser" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "Open Terminal" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"), { description = "Open File Manager" })

-- 3. Window Management
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close(), { repeating = true, description = "Close active window" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating mode" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen(), { description = "Toggle fullscreen mode" })

hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Drag window" })
hl.unbind("SUPER + ALT + mouse:272")
hl.bind("SUPER + ALT + mouse:272", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

-- 4. Workspaces
hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }), { description = "Focus workspace 1" })
hl.unbind("SUPER + 2")
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }), { description = "Focus workspace 2" })
hl.unbind("SUPER + 3")
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }), { description = "Focus workspace 3" })
hl.unbind("SUPER + 4")
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }), { description = "Focus workspace 4" })
hl.unbind("SUPER + 5")
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }), { description = "Focus workspace 5" })
hl.unbind("SUPER + 6")
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }), { description = "Focus workspace 6" })
hl.unbind("SUPER + 7")
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }), { description = "Focus workspace 7" })
hl.unbind("SUPER + 8")
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }), { description = "Focus workspace 8" })
hl.unbind("SUPER + 9")
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }), { description = "Focus workspace 9" })
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }), { description = "Focus workspace 10" })

hl.unbind("SUPER + ALT + 1")
hl.bind("SUPER + ALT + 1", hl.dsp.window.move({ workspace = 1 }), { description = "Move window to workspace 1" })
hl.unbind("SUPER + ALT + 2")
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = 2 }), { description = "Move window to workspace 2" })
hl.unbind("SUPER + ALT + 3")
hl.bind("SUPER + ALT + 3", hl.dsp.window.move({ workspace = 3 }), { description = "Move window to workspace 3" })
hl.unbind("SUPER + ALT + 4")
hl.bind("SUPER + ALT + 4", hl.dsp.window.move({ workspace = 4 }), { description = "Move window to workspace 4" })
hl.unbind("SUPER + ALT + 5")
hl.bind("SUPER + ALT + 5", hl.dsp.window.move({ workspace = 5 }), { description = "Move window to workspace 5" })
hl.unbind("SUPER + ALT + 6")
hl.bind("SUPER + ALT + 6", hl.dsp.window.move({ workspace = 6 }), { description = "Move window to workspace 6" })
hl.unbind("SUPER + ALT + 7")
hl.bind("SUPER + ALT + 7", hl.dsp.window.move({ workspace = 7 }), { description = "Move window to workspace 7" })
hl.unbind("SUPER + ALT + 8")
hl.bind("SUPER + ALT + 8", hl.dsp.window.move({ workspace = 8 }), { description = "Move window to workspace 8" })
hl.unbind("SUPER + ALT + 9")
hl.bind("SUPER + ALT + 9", hl.dsp.window.move({ workspace = 9 }), { description = "Move window to workspace 9" })
hl.unbind("SUPER + ALT + 0")
hl.bind("SUPER + ALT + 0", hl.dsp.window.move({ workspace = 10 }), { description = "Move window to workspace 10" })

hl.unbind("SUPER + minus")
hl.bind("SUPER + minus", function() hl.dispatch("hyprexpo:expo", "toggle") end, { description = "Toggle Workspace Overview" })

-- 5. Focus & Movement
hl.unbind("SUPER + Left")
hl.bind("SUPER + Left", function() hl.dispatch("movefocus", "l") end, { description = "Focus window left" })
hl.unbind("SUPER + Right")
hl.bind("SUPER + Right", function() hl.dispatch("movefocus", "r") end, { description = "Focus window right" })
hl.unbind("SUPER + Up")
hl.bind("SUPER + Up", function() hl.dispatch("movefocus", "u") end, { description = "Focus window up" })
hl.unbind("SUPER + Down")
hl.bind("SUPER + Down", function() hl.dispatch("movefocus", "d") end, { description = "Focus window down" })

hl.unbind("SUPER + SHIFT + Left")
hl.bind("SUPER + SHIFT + Left", function() hl.dispatch("movewindow", "l") end, { description = "Move window left" })
hl.unbind("SUPER + SHIFT + Right")
hl.bind("SUPER + SHIFT + Right", function() hl.dispatch("movewindow", "r") end, { description = "Move window right" })
hl.unbind("SUPER + SHIFT + Up")
hl.bind("SUPER + SHIFT + Up", function() hl.dispatch("movewindow", "u") end, { description = "Move window up" })
hl.unbind("SUPER + SHIFT + Down")
hl.bind("SUPER + SHIFT + Down", function() hl.dispatch("movewindow", "d") end, { description = "Move window down" })

-- 6. Special Workspace (Scratchpad)
hl.unbind("SUPER + S")
hl.bind("SUPER + S", function() hl.dispatch("togglespecialworkspace", "magic") end, { description = "Toggle scratchpad" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", function() hl.dispatch("movetoworkspace", "special:magic") end, { description = "Move window to scratchpad" })

-- 7. Media & Hardware
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, description = "Volume Up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, description = "Volume Down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { description = "Toggle Mute" })

-- 8. Utilities
hl.bind("SUPER + C", hl.dsp.exec_cmd("hyprpicker -a"), { description = "Color Picker" })
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("noctalia msg panel-toggle session"), { description = "Power Menu" })
hl.bind("SUPER + U", function() hl.dispatch("movefocus", "u") end)
