-- binds.lua

hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"), { release = true })

-- Keybinds from hyprland-custom.lua
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close(), { repeating = true })

hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.unbind("SUPER + 2")
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.unbind("SUPER + 3")
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.unbind("SUPER + 4")
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.unbind("SUPER + 5")
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.unbind("SUPER + 6")
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.unbind("SUPER + 7")
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.unbind("SUPER + 8")
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.unbind("SUPER + 9")
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))

hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("zen-browser"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))

hl.unbind("SUPER + ALT + 1")
hl.bind("SUPER + ALT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.unbind("SUPER + ALT + 2")
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.unbind("SUPER + ALT + 3")
hl.bind("SUPER + ALT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.unbind("SUPER + ALT + 4")
hl.bind("SUPER + ALT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.unbind("SUPER + ALT + 5")
hl.bind("SUPER + ALT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.unbind("SUPER + ALT + 6")
hl.bind("SUPER + ALT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.unbind("SUPER + ALT + 7")
hl.bind("SUPER + ALT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.unbind("SUPER + ALT + 8")
hl.bind("SUPER + ALT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.unbind("SUPER + ALT + 9")
hl.bind("SUPER + ALT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.unbind("SUPER + ALT + 0")
hl.bind("SUPER + ALT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.unbind("SUPER + slash")
hl.bind("SUPER + slash", hl.dsp.exec_cmd("noctalia msg panel-toggle kenn/keybind-cheatsheet:cheatsheet"))
hl.unbind("CTRL + Insert")
hl.bind("CTRL + Insert", hl.dsp.exec_cmd("noctalia msg screenshot-region"))
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen())

hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.unbind("SUPER + ALT + mouse:272")
hl.bind("SUPER + ALT + mouse:272", hl.dsp.window.resize(), { mouse = true })

hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
